[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
